version: '3.7'

networks:
  minima_testnet:
    name: minima_testnet
  outside_minima_testnet:
    name: outside_minima_testnet

services:
  minima_one:
    image: minima:latest
    command: -private -automine -test -clean
    networks:
      minima_testnet:
        aliases:
          - minima_one
    ports:
      - "9001:9001"
      - "9002:9002"
      - "9003:9003"
      - "9004:9004"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 500M

  minima_peer:
    image: minima:latest
    command: -test -clean -connect minima_one 9001
    networks:
      minima_testnet:
        aliases:
          - minima_peer
    depends_on:
      - minima_one
    ports:
      - "7100-7110:9001"
      - "7200-7210:9002"
      - "7300-7310:9003"
      - "7400-7410:9004"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 400M
  minima_client:
    image: minima:latest
    command: -test -clean -isclient -connect minima_one 9001
    networks:
      minima_testnet:
        aliases:
          - minima_peer
    depends_on:
      - minima_one
    ports:
      - "6100-6110:9001"
      - "6200-6210:9002"
      - "6300-6310:9003"
      - "6400-6410:9004"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 400M
  minima_client_firewall:
    image: minima:latest
    command: -test -clean -connect host.docker.internal 9001 -port 9055
    networks:
      outside_minima_testnet:
    depends_on:
      - minima_one
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 400M
